name: demy_teachers
description: Flutter module for Demy Teachers app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  logger: ^2.6.2
  get_it: ^8.2.0
  injectable: ^2.5.2
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_foreground.png"
  adaptive_icon_background: "assets/icons/ic_background.png"
  adaptive_icon_foreground: "assets/icons/ic_foreground.png"
  image_path_ios: "assets/icons/ic_ios_full.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#3F51B5"
  image: assets/icons/ic_foreground_small.png
  branding: assets/icons/ic_brand_text.png
  branding_mode: bottom
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    color: "#3F51B5"
    image: assets/icons/ic_foreground_small.png
    icon_background_color: "#3F51B5"
    branding: assets/icons/ic_brand_text.png
    branding_mode: bottom