name: demy_teachers
description: Flutter module for Demy Teachers app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  logger: ^2.6.2
  get_it: ^8.2.0
  injectable: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true